#%RAML 1.0
title: customerApi

description: This is the customer API to manage the customer data.

/customer:
  get:
    description: This is the method to get the details about the customer.
    queryParameters:
      id:
        required: true
        example: "12345"
    responses:
      200:
       body:
         application/json:
           example:
             {
               "firstname":"test1",
               "lstname":"test2"
             }
      500:
        body:
          application/json:
            example:
              :"Internal Error"
  post:
    description: This method the method receive the data from the user.
    body:
      application/json:
        example:
           {
               "firstname":"test1",
               "lstname":"test2"
            }
       

          
             
